# Generated by Django 3.1.6 on 2021-02-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_follow_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
    ]
