# Generated by Django 3.1.6 on 2021-02-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210215_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='subscribe_date',
        ),
    ]
